# Run by `cmake -P` from the custom command in ShapeshifterShaders.cmake.
# Copies both shader trees into one staged root, hashes the result, and writes
# the hash to a generated header and to MANIFEST beside the staged tree.
#
# Inputs: EDITOR_SHADERS, COMMON_SLANG, STAGED, GEN_HEADER.

# copy_if_different rather than a wholesale copy_directory: an unchanged file
# keeps its timestamp, so nothing downstream of the staged tree rebuilds for a
# shader that did not actually change.
#
# EVERY file, not just *.slang and *.h. Whatever lands here is bundled and is
# readable by the compiler at run time, so restricting the copy by extension
# would only mean shipping files the hash below does not cover. The one
# exclusion is dotfiles: .DS_Store appearing because someone opened the folder
# in Finder must not restage, rehash and relink the editor.
function(stage_tree src dest_prefix out_expected)
    set(expected "")
    # GLOB_RECURSE, and recursive for BOTH trees: plain GLOB is non-recursive
    # and, unlike GLOB_RECURSE, lists directories -- `cmake -E copy_if_different`
    # on a directory fails, and the directory name would still be recorded as
    # expected, so the prune below would keep it forever.
    file(GLOB_RECURSE files RELATIVE ${src} ${src}/*)
    foreach(rel ${files})
        get_filename_component(name ${rel} NAME)
        if(name MATCHES "^\\.")
            continue()
        endif()
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different
                        ${src}/${rel} ${STAGED}/${dest_prefix}${rel}
                        RESULT_VARIABLE rc)
        # CHECKED. A failed copy used to be silent, which meant the file simply
        # never reached the staged tree, was never hashed, and the app failed to
        # resolve it at run time with nothing anywhere saying why.
        if(NOT rc EQUAL 0)
            message(FATAL_ERROR "staging failed to copy ${src}/${rel} (${rc})")
        endif()
        list(APPEND expected ${dest_prefix}${rel})
    endforeach()
    set(${out_expected} "${expected}" PARENT_SCOPE)
endfunction()

stage_tree(${EDITOR_SHADERS} "" EDITOR_EXPECTED)
stage_tree(${COMMON_SLANG} "common/" COMMON_EXPECTED)
set(EXPECTED ${EDITOR_EXPECTED} ${COMMON_EXPECTED})

# PRUNE, because copy_if_different only ever adds. A shader deleted from the
# repo would otherwise sit in the staged tree forever: hashed, bundled, and
# compiled by a `import` that still resolves -- a stale file surviving its own
# deletion is exactly the class of desync this whole mechanism exists to end.
file(GLOB_RECURSE STAGED_NOW RELATIVE ${STAGED} ${STAGED}/*)
foreach(rel ${STAGED_NOW})
    if(NOT rel STREQUAL "MANIFEST")
        list(FIND EXPECTED ${rel} idx)
        if(idx EQUAL -1)
            file(REMOVE ${STAGED}/${rel})
        endif()
    endif()
endforeach()

# Hash the STAGED tree, not the sources. It is what will actually be read, so
# hashing it is what makes the manifest a statement about the bytes in use --
# and it means a staging bug shows up as a mismatch rather than passing.
#
# GLOBbed here rather than handed in as a list: the covered set is DERIVED, so a
# newly added shader is hashed without anyone remembering to register it.
#
# EVERY staged file, not *.slang and *.h. Restricting it by extension meant a
# `.slangh`, a data file, anything else shipped INSIDE the bundle while
# contributing nothing to the hash -- measured: the file was staged, bundled and
# tracked edits, and the manifest never moved. "The bundle matches the binary"
# has to mean the whole bundle.
file(GLOB_RECURSE STAGED_FILES ${STAGED}/*)
list(REMOVE_ITEM STAGED_FILES ${STAGED}/MANIFEST) # written below, from this hash
list(SORT STAGED_FILES)
set(ACC "")
foreach(f ${STAGED_FILES})
    file(SHA256 ${f} H)
    file(RELATIVE_PATH REL ${STAGED} ${f})
    # Path AND content: a rename with identical bytes still changes the tree.
    string(APPEND ACC "${REL}:${H}\n")
endforeach()
string(SHA256 TREE_HASH "${ACC}")

file(WRITE ${STAGED}/MANIFEST "${TREE_HASH}\n")

set(HEADER_TEXT
"// GENERATED by cmake/StageShapeshifterShaders.cmake. Do not edit.
//
// The content hash of the staged shader tree, baked into the binary so a
// binary reading a tree it was not built against can say so.
#pragma once
#define SHAPESHIFTER_SHADER_HASH \"${TREE_HASH}\"
")

# WRITTEN ONLY ON CHANGE. This command re-runs whenever a dependency's
# timestamp moves, which includes a `touch` that changed nothing -- rewriting
# the header there would recompile and relink the world for no reason.
set(OLD "")
if(EXISTS ${GEN_HEADER})
    file(READ ${GEN_HEADER} OLD)
endif()
if(NOT OLD STREQUAL HEADER_TEXT)
    file(WRITE ${GEN_HEADER} "${HEADER_TEXT}")
    message(STATUS "shapeshifter shader tree: ${TREE_HASH}")
endif()
