# Run by `cmake -P` from the custom command in ShapeshifterShaders.cmake.
# Copies both shader trees into one staged root, hashes the result, and writes
# the hash to a generated header and to MANIFEST beside the staged tree.
#
# Inputs: EDITOR_SHADERS, COMMON_SLANG, STAGED, GEN_HEADER.

# copy_if_different rather than a wholesale copy_directory: an unchanged file
# keeps its timestamp, so nothing downstream of the staged tree rebuilds for a
# shader that did not actually change.
set(EXPECTED "")
file(GLOB_RECURSE EDITOR_FILES RELATIVE ${EDITOR_SHADERS} ${EDITOR_SHADERS}/*)
foreach(rel ${EDITOR_FILES})
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different
                    ${EDITOR_SHADERS}/${rel} ${STAGED}/${rel})
    list(APPEND EXPECTED ${rel})
endforeach()
file(GLOB COMMON_FILES RELATIVE ${COMMON_SLANG} ${COMMON_SLANG}/*)
foreach(rel ${COMMON_FILES})
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different
                    ${COMMON_SLANG}/${rel} ${STAGED}/common/${rel})
    list(APPEND EXPECTED common/${rel})
endforeach()

# PRUNE, because copy_if_different only ever adds. A shader deleted from the
# repo would otherwise sit in the staged tree forever: hashed, bundled, and
# compiled by a `import` that still resolves -- a stale file surviving its own
# deletion is exactly the class of desync this whole mechanism exists to end.
file(GLOB_RECURSE STAGED_NOW RELATIVE ${STAGED} ${STAGED}/*)
foreach(rel ${STAGED_NOW})
    if(NOT rel STREQUAL "MANIFEST")
        list(FIND EXPECTED ${rel} idx)
        if(idx EQUAL -1)
            file(REMOVE ${STAGED}/${rel})
        endif()
    endif()
endforeach()

# Hash the STAGED tree, not the sources. It is what will actually be read, so
# hashing it is what makes the manifest a statement about the bytes in use --
# and it means a staging bug shows up as a mismatch rather than passing.
#
# GLOBbed here rather than handed in as a list: the covered set is DERIVED, so a
# newly added shader is hashed without anyone remembering to register it.
file(GLOB_RECURSE STAGED_FILES ${STAGED}/*.slang ${STAGED}/*.h)
list(SORT STAGED_FILES)
set(ACC "")
foreach(f ${STAGED_FILES})
    file(SHA256 ${f} H)
    file(RELATIVE_PATH REL ${STAGED} ${f})
    # Path AND content: a rename with identical bytes still changes the tree.
    string(APPEND ACC "${REL}:${H}\n")
endforeach()
string(SHA256 TREE_HASH "${ACC}")

file(WRITE ${STAGED}/MANIFEST "${TREE_HASH}\n")

set(HEADER_TEXT
"// GENERATED by cmake/StageShapeshifterShaders.cmake. Do not edit.
//
// The content hash of the staged shader tree, baked into the binary so a
// binary reading a tree it was not built against can say so.
#pragma once
#define SHAPESHIFTER_SHADER_HASH \"${TREE_HASH}\"
")

# WRITTEN ONLY ON CHANGE. This command re-runs whenever a dependency's
# timestamp moves, which includes a `touch` that changed nothing -- rewriting
# the header there would recompile and relink the world for no reason.
set(OLD "")
if(EXISTS ${GEN_HEADER})
    file(READ ${GEN_HEADER} OLD)
endif()
if(NOT OLD STREQUAL HEADER_TEXT)
    file(WRITE ${GEN_HEADER} "${HEADER_TEXT}")
    message(STATUS "shapeshifter shader tree: ${TREE_HASH}")
endif()
